name: PR Checks
on: pull_request
env:
  node_version: 22.x
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
      - name: Setup Node.js ${{ env.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          cache: 'pnpm'
      - name: Install dependencies and build
        run: pnpm install
      - name: Archive dependencies
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: pnpm-dependencies-${{ env.node_version }}-${{ github.run_id }}
          path: |
            node_modules
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ env.node_version }}-${{ github.run_id }}
          path: |
            **/dist
            !node_modules
            !**/dist/**/*.d.ts
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
      - name: Setup Node.js ${{ env.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          cache: 'pnpm'
      - name: Download dependencies
        uses: actions/download-artifact@v4
        with:
          name: pnpm-dependencies-${{ env.node_version }}-${{ github.run_id }}
      - name: Lint
        run: pnpm lint
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
      - name: Setup Node.js ${{ env.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          cache: 'pnpm'
      - name: Download dependencies
        uses: actions/download-artifact@v4
      - name: Test
        run: pnpm test
